/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class lfht {
  public static SWIGTYPE_p_dic_ptr dic_check_insert_key(int arg0, int arg1, SWIGTYPE_p_LFHT_ThreadEnvPtr arg2) {
    return new SWIGTYPE_p_dic_ptr(lfhtJNI.dic_check_insert_key(arg0, arg1, SWIGTYPE_p_LFHT_ThreadEnvPtr.getCPtr(arg2)), true);
  }

  public static SWIGTYPE_p_dic_ptr dic_check_delete_key(int arg0, int arg1, SWIGTYPE_p_LFHT_ThreadEnvPtr arg2) {
    return new SWIGTYPE_p_dic_ptr(lfhtJNI.dic_check_delete_key(arg0, arg1, SWIGTYPE_p_LFHT_ThreadEnvPtr.getCPtr(arg2)), true);
  }

  public static void dic_show_state(String arg0) {
    lfhtJNI.dic_show_state(arg0);
  }

  public static void dic_show_statistics(String arg0) {
    lfhtJNI.dic_show_statistics(arg0);
  }

  public static void dic_abolish_all_keys() {
    lfhtJNI.dic_abolish_all_keys();
  }

  public static void dic_show_delete_pool(String arg0) {
    lfhtJNI.dic_show_delete_pool(arg0);
  }

  public static void dic_create_init_env() {
    lfhtJNI.dic_create_init_env();
  }

  public static SWIGTYPE_p_LFHT_ThreadEnvPtr dic_create_init_thread_env(int arg0) {
    return new SWIGTYPE_p_LFHT_ThreadEnvPtr(lfhtJNI.dic_create_init_thread_env(arg0), true);
  }

  public static void dic_kill_thread_env(int arg0) {
    lfhtJNI.dic_kill_thread_env(arg0);
  }

}
