/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class lfhtJNI {
  public final static native long dic_check_insert_key(int jarg1, int jarg2, long jarg3);
  public final static native long dic_check_delete_key(int jarg1, int jarg2, long jarg3);
  public final static native void dic_show_state(String jarg1);
  public final static native void dic_show_statistics(String jarg1);
  public final static native void dic_abolish_all_keys();
  public final static native void dic_show_delete_pool(String jarg1);
  public final static native void dic_create_init_env();
  public final static native long dic_create_init_thread_env(int jarg1);
  public final static native void dic_kill_thread_env(int jarg1);
}
